language: cpp
sudo: required

matrix:
  include:
    # Linux and GCC
    - os: linux
      dist: xenial
      env:
        - CC_COMPILER=gcc-6
        - CXX_COMPILER=g++-6
      script:
        - git submodule init
        - git submodule update
        - export PATH=/usr/bin/:$PATH 
        - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
        - sudo apt-get update
        - wget https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS-2019.PUB
        - sudo apt-key add GPG-PUB-KEY-INTEL-SW-PRODUCTS-2019.PUB
        - sudo sh -c 'echo deb https://apt.repos.intel.com/mkl all main > /etc/apt/sources.list.d/intel-mkl.list'
        - sudo apt-get update
        - cd ModalSound
        - chmod 755 get_eigen.sh
        - ./get_eigen.sh
        - sudo apt-get install -y gcc-6 g++-6
        - sudo apt-get install -y cmake cmake-data git libboost-all-dev xorg-dev libglu1-mesa-dev libgoogle-glog-dev freeglut3-dev qtmultimedia5-dev  qt5-default mesa-utils libqglviewer-dev  libxmu-dev libxi-dev libconfig++-dev libprotobuf-dev libgsl-dev protobuf-compiler 
        - sudo apt-get install intel-mkl-64bit-2017.4-061
        - cmake --version
        - source /opt/intel/mkl/bin/mklvars.sh intel64
        - source /opt/intel/bin/compilervars.sh intel64
        - mkdir build
        - cd build
        - CC=$CC_COMPILER CXX=$CXX_COMPILER cmake ..
        - make 
        - cd ../../IsoStuffer
        - mkdir build
        - cd build
        - CC=$CC_COMPILER CXX=$CXX_COMPILER cmake ..
        - make -j 2
      #  - $CTEST_EXEC -j 2 --output-on-failure
      #     - os: osx
      #       compiler: clang
      #       script:
      #         - cmake --version
      #         - git submodule init
      #         - git submodule update
      #         - mkdir build
      #         - cd build
      #         - cmake ..
      #         - make -j 2

